# Generated by Django 2.2 on 2020-11-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
