# Generated by Django 2.2 on 2020-11-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employee_cell_phone',
            field=models.CharField(blank=True, default=' ', max_length=10, null=True),
        ),
    ]
