# Generated by Django 2.2 on 2020-10-24 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('O Positive', 'O Positive'), ('O Negative', 'O Negative'), ('A Positive', 'A Positive'), ('A Negative', 'A Negative'), ('B Positive', 'B Positive'), ('B Negative', 'B Negative'), ('AB Negative', 'AB Negative'), ('AB Positive', 'AB Positive')], default='O Positive', max_length=20)),
                ('units', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['-units'],
            },
        ),
        migrations.CreateModel(
            name='DonarDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(default=' ', max_length=50)),
                ('id_no', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('blood_group', models.CharField(choices=[('O Positive', 'O Positive'), ('O Negative', 'O Negative'), ('A Positive', 'A Positive'), ('A Negative', 'A Negative'), ('B Positive', 'B Positive'), ('B Negative', 'B Negative'), ('AB Negative', 'AB Negative'), ('AB Positive', 'AB Positive')], default='O Positive', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('street', models.CharField(max_length=20, verbose_name='Street Number')),
                ('street1', models.CharField(max_length=40, verbose_name='Street Name')),
                ('street2', models.CharField(blank=True, max_length=40, verbose_name='Street Name 2')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('registered_by', models.CharField(default='Admin', max_length=20)),
                ('contact_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('last_donated_date', models.CharField(default='0', max_length=20)),
                ('number_month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_TYPE', models.CharField(choices=[('O Positive', 'O Positive'), ('O Negative', 'O Negative'), ('A Positive', 'A Positive'), ('A Negative', 'A Negative'), ('B Positive', 'B Positive'), ('B Negative', 'B Negative'), ('AB Negative', 'AB Negative'), ('AB Positive', 'AB Positive')], default='O Positive', max_length=20)),
                ('staff', models.CharField(default=' ', max_length=20)),
                ('id_no', models.CharField(default=' ', max_length=20)),
                ('donar_name', models.CharField(max_length=30)),
                ('units', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
