# Generated by Django 2.2 on 2021-01-26 21:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('O Positive', 'O Positive'), ('O Negative', 'O Negative'), ('A Positive', 'A Positive'), ('A Negative', 'A Negative'), ('B Positive', 'B Positive'), ('B Negative', 'B Negative'), ('AB Negative', 'AB Negative'), ('AB Positive', 'AB Positive')], default='O Positive', max_length=20)),
                ('units', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['-units'],
            },
        ),
        migrations.CreateModel(
            name='DonarDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('blood_group', models.CharField(choices=[('O Positive', 'O Positive'), ('O Negative', 'O Negative'), ('A Positive', 'A Positive'), ('A Negative', 'A Negative'), ('B Positive', 'B Positive'), ('B Negative', 'B Negative'), ('AB Negative', 'AB Negative'), ('AB Positive', 'AB Positive')], default='O Positive', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('street', models.CharField(max_length=20, verbose_name='Address 1')),
                ('street1', models.CharField(max_length=40, verbose_name='Address 2')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('zipcode', models.IntegerField(validators=[django.core.validators.MinValueValidator(5)])),
                ('registered_by', models.CharField(default='Admin', max_length=20)),
                ('contact_number', models.CharField(blank=True, default=' ', max_length=10, null=True)),
                ('last_donated_date', models.DateField()),
                ('number_month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_TYPE', models.CharField(choices=[('O Positive', 'O Positive'), ('O Negative', 'O Negative'), ('A Positive', 'A Positive'), ('A Negative', 'A Negative'), ('B Positive', 'B Positive'), ('B Negative', 'B Negative'), ('AB Negative', 'AB Negative'), ('AB Positive', 'AB Positive')], default='O Positive', max_length=20)),
                ('units', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField()),
                ('donar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donar_id', to='registration.DonarDetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
