# Generated by Django 2.2 on 2020-10-24 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donardetail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='donardetail',
            name='street2',
        ),
        migrations.AddField(
            model_name='donardetail',
            name='state',
            field=models.CharField(max_length=2, verbose_name='State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donardetail',
            name='zipcode',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donardetail',
            name='last_donated_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='donardetail',
            name='street',
            field=models.CharField(max_length=20, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='donardetail',
            name='street1',
            field=models.CharField(max_length=40, verbose_name='Address 2'),
        ),
    ]
