# Generated by Django 2.2 on 2020-10-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20201023_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donardetail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='donardetail',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
