# Generated by Django 2.2 on 2020-10-26 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0001_initial'),
        ('registration', '0003_auto_20201023_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='donar_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='id_no',
        ),
        migrations.RemoveField(
            model_name='record',
            name='staff',
        ),
        migrations.AddField(
            model_name='bloodstorage',
            name='bloodrequest_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bloodrequest_id', to='storage.Request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='donar_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='donar_id', to='registration.DonarDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
