# Generated by Django 2.2 on 2020-10-26 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20201025_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodstorage',
            old_name='bloodrequest_id',
            new_name='bloodrequest',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='donar_id',
            new_name='donar',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='user_id',
            new_name='user',
        ),
    ]
