# Generated by Django 2.2 on 2020-11-15 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_remove_bloodstorage_bloodrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donardetail',
            name='id_no',
        ),
    ]
